version: "3.8"

services:

  yappy-app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: yappy.dockerfile
    container_name: yappy-app
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - yappy-network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: yappy-prometheus
    hostname: prometheus
    ports:
      - '9092:9092'
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.listen-address=:9092'
    networks:
      - yappy-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: yappy-grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - yappy-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - yappy-network

networks:
  yappy-network:
    name: yappy-network