---
- name: Копирование конфига для мониторинга
  hosts: yappy
  become: true

  roles:
    - role: ../roles/copy_conf

- name: Деплой приложения с помощью Docker Compose
  hosts: yappy
  become: true

  roles:
    - role: ../roles/deploy_docker_compose