- name: Создание каталога для приложения
  file:
    path: /opt/yappy
    state: directory

- name: Копирование docker-compose.yml в каталог приложения
  template:
    src: docker-compose.yml.j2
    dest: /opt/yappy/docker-compose.yml

- name: Запуск приложения с помощью docker-compose
  docker_compose:
    project_src: /opt/yappy